-- Market2Lead generated DAX measure catalog
-- Demo value column: ProcessCases[CampaignSpend]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total CampaignSpend = SUM('ProcessCases'[CampaignSpend])

Campaign ROI = SUM('ProcessCases'[CampaignSpend])
MQL Conversion = SUM('ProcessCases'[CampaignSpend])
CAC = SUM('ProcessCases'[CampaignSpend])
Lead Velocity = SUM('ProcessCases'[CampaignSpend])
Qualified Pipeline = SUM('ProcessCases'[CampaignSpend])
