-- Dock2Stock generated DAX measure catalog
-- Demo value column: ProcessCases[InboundValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total InboundValue = SUM('ProcessCases'[InboundValue])

Dock-to-Stock Time = AVERAGE('ProcessCases'[ActualCycleDays])
GR Accuracy = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Inspection Aging = AVERAGE('ProcessCases'[ActualCycleDays])
Putaway Backlog = SUM('ProcessCases'[InboundValue])
Blocked Stock Value = SUM('ProcessCases'[InboundValue])
