-- Lead2Quote / Configure2Quote generated DAX measure catalog
-- Demo value column: ProcessCases[QuoteValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total QuoteValue = SUM('ProcessCases'[QuoteValue])

Quote Cycle Time = AVERAGE('ProcessCases'[ActualCycleDays])
Configuration Error Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Approval Aging = AVERAGE('ProcessCases'[ActualCycleDays])
Discount Leakage = COUNTROWS('ProcessCases')
Quote Win Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
