-- Data2Insight2Action generated DAX measure catalog
-- Demo value column: ProcessCases[RealizedValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total RealizedValue = SUM('ProcessCases'[RealizedValue])

Insight Adoption = SUM('ProcessCases'[RealizedValue])
Action Conversion = SUM('ProcessCases'[RealizedValue])
Decision Latency = AVERAGE('ProcessCases'[ActualCycleDays])
Realized Value = SUM('ProcessCases'[RealizedValue])
Action Overdue Count = COUNTROWS('ProcessCases')
