-- Complaint2CAPA generated DAX measure catalog
-- Demo value column: ProcessCases[QualityCost]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total QualityCost = SUM('ProcessCases'[QualityCost])

Complaint Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
CAPA Aging = AVERAGE('ProcessCases'[ActualCycleDays])
Repeat Defect Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Cost Of Poor Quality = SUM('ProcessCases'[QualityCost])
CAPA Effectiveness = SUM('ProcessCases'[QualityCost])
