-- InstalledBase2ServiceRevenue generated DAX measure catalog
-- Demo value column: ProcessCases[ServiceRevenue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total ServiceRevenue = SUM('ProcessCases'[ServiceRevenue])

Attach Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
SLA Adherence = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Service Margin = SUM('ProcessCases'[ServiceRevenue])
Renewal Opportunity = SUM('ProcessCases'[ServiceRevenue])
Coverage Gap = SUM('ProcessCases'[ServiceRevenue])
