-- Idea2Launch / Engineer2Release generated DAX measure catalog
-- Demo value column: ProcessCases[LaunchValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total LaunchValue = SUM('ProcessCases'[LaunchValue])

Gate Adherence = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Change Backlog = SUM('ProcessCases'[LaunchValue])
Launch Risk = AVERAGE('ProcessCases'[RiskScore])
Ramp-Up Readiness = SUM('ProcessCases'[LaunchValue])
Engineering Cycle Time = AVERAGE('ProcessCases'[ActualCycleDays])
