-- Engineer2Order / Project2Cash generated DAX measure catalog
-- Demo value column: ProcessCases[ProjectValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total ProjectValue = SUM('ProcessCases'[ProjectValue])

Milestone Adherence = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Project Margin = SUM('ProcessCases'[ProjectValue])
WIP Value = SUM('ProcessCases'[ProjectValue])
Billing Readiness = SUM('ProcessCases'[ProjectValue])
Cash Exposure = SUM('ProcessCases'[ProjectValue])
