table Dim_Calendar
	lineageTag: a18c47e7-76b7-52bb-a315-dda4f25fcf33

	column Date
		dataType: dateTime
		sourceColumn: [Date]

	column Year
		dataType: int64
		sourceColumn: [Year]

	column Quarter
		dataType: string
		sourceColumn: [Quarter]

	column MonthNo
		dataType: int64
		sourceColumn: [MonthNo]

	column MonthName
		dataType: string
		sourceColumn: [MonthName]

	column FiscalYear
		dataType: int64
		sourceColumn: [FiscalYear]

	column FiscalPeriod
		dataType: int64
		sourceColumn: [FiscalPeriod]

	column IsWorkingDay
		dataType: string
		sourceColumn: [IsWorkingDay]

	partition Dim_Calendar = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("C:/tmp/PowerBi-Codex-Plugin/outputs/powerbi-industrial-demo/powerbi_industrial_demo_data.xlsx"), null, true),
			    Raw = Source{[Item="Dim_Calendar", Kind="Sheet"]}[Data],
			    PromotedHeaders = Table.PromoteHeaders(Raw, [PromoteAllScalars = true]),
			    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"MonthNo", Int64.Type}, {"MonthName", type text}, {"FiscalYear", Int64.Type}, {"FiscalPeriod", Int64.Type}, {"IsWorkingDay", type text}}, "en-US")
			in
			    ChangedType
