table Dim_Product
	lineageTag: a0dff1fd-a643-55c4-bbd1-1d063807a9ff

	column ProductID
		dataType: string
		sourceColumn: [ProductID]

	column ProductName
		dataType: string
		sourceColumn: [ProductName]

	column ProductFamily
		dataType: string
		sourceColumn: [ProductFamily]

	column ProductLine
		dataType: string
		sourceColumn: [ProductLine]

	column LifecycleStatus
		dataType: string
		sourceColumn: [LifecycleStatus]

	column StandardCost
		dataType: double
		sourceColumn: [StandardCost]

	column ListPrice
		dataType: double
		sourceColumn: [ListPrice]

	partition Dim_Product = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("C:/tmp/PowerBi-Codex-Plugin/outputs/powerbi-industrial-demo/powerbi_industrial_demo_data.xlsx"), null, true),
			    Raw = Source{[Item="Dim_Product", Kind="Sheet"]}[Data],
			    PromotedHeaders = Table.PromoteHeaders(Raw, [PromoteAllScalars = true]),
			    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"ProductID", type text}, {"ProductName", type text}, {"ProductFamily", type text}, {"ProductLine", type text}, {"LifecycleStatus", type text}, {"StandardCost", type number}, {"ListPrice", type number}}, "en-US")
			in
			    ChangedType
