table Fact_Order2CashExceptions
	lineageTag: 108e53ea-7fef-5d70-91fe-25e6a1fbd138

	column ExceptionID
		dataType: string
		sourceColumn: [ExceptionID]

	column ProblemType
		dataType: string
		sourceColumn: [ProblemType]

	column Severity
		dataType: string
		sourceColumn: [Severity]

	column CustomerID
		dataType: string
		sourceColumn: [CustomerID]

	column ProductID
		dataType: string
		sourceColumn: [ProductID]

	column RelatedDocument
		dataType: string
		sourceColumn: [RelatedDocument]

	column EventDate
		dataType: dateTime
		sourceColumn: [EventDate]

	column AmountExposure
		dataType: double
		sourceColumn: [AmountExposure]

	column Reason
		dataType: string
		sourceColumn: [Reason]

	column RecommendedAction
		dataType: string
		sourceColumn: [RecommendedAction]

	column OwnerRole
		dataType: string
		sourceColumn: [OwnerRole]

	partition Fact_Order2CashExceptions = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:/tmp/PowerBi-Codex-Plugin/outputs/powerbi-order2cash-test/data/Fact_Order2CashExceptions.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
			    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"ExceptionID", type text}, {"ProblemType", type text}, {"Severity", type text}, {"CustomerID", type text}, {"ProductID", type text}, {"RelatedDocument", type text}, {"EventDate", type date}, {"AmountExposure", type number}, {"Reason", type text}, {"RecommendedAction", type text}, {"OwnerRole", type text}}, "en-US")
			in
			    ChangedType
