table Fact_Billing
	lineageTag: 5bd749af-4621-5fd4-8727-987a816de993

	column InvoiceID
		dataType: string
		sourceColumn: [InvoiceID]

	column DeliveryID
		dataType: string
		sourceColumn: [DeliveryID]

	column SalesOrderID
		dataType: string
		sourceColumn: [SalesOrderID]

	column CustomerID
		dataType: string
		sourceColumn: [CustomerID]

	column InvoiceDate
		dataType: dateTime
		sourceColumn: [InvoiceDate]

	column DueDate
		dataType: dateTime
		sourceColumn: [DueDate]

	column InvoiceAmount
		dataType: double
		sourceColumn: [InvoiceAmount]

	column TaxAmount
		dataType: double
		sourceColumn: [TaxAmount]

	column BillingBlockFlag
		dataType: boolean
		sourceColumn: [BillingBlockFlag]

	partition Fact_Billing = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("C:/tmp/PowerBi-Codex-Plugin/outputs/powerbi-industrial-demo/powerbi_industrial_demo_data.xlsx"), null, true),
			    Raw = Source{[Item="Fact_Billing", Kind="Sheet"]}[Data],
			    PromotedHeaders = Table.PromoteHeaders(Raw, [PromoteAllScalars = true]),
			    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"InvoiceID", type text}, {"DeliveryID", type text}, {"SalesOrderID", type text}, {"CustomerID", type text}, {"InvoiceDate", type date}, {"DueDate", type date}, {"InvoiceAmount", type number}, {"TaxAmount", type number}, {"BillingBlockFlag", type logical}}, "en-US")
			in
			    ChangedType
