table Fact_AR
	lineageTag: 05e051f2-58ef-5fb3-bd61-bf751be090b5

	column InvoiceID
		dataType: string
		sourceColumn: [InvoiceID]

	column CustomerID
		dataType: string
		sourceColumn: [CustomerID]

	column DueDate
		dataType: dateTime
		sourceColumn: [DueDate]

	column OpenAmount
		dataType: double
		sourceColumn: [OpenAmount]

	column PaymentDate
		dataType: dateTime
		sourceColumn: [PaymentDate]

	column DisputeFlag
		dataType: boolean
		sourceColumn: [DisputeFlag]

	column DunningLevel
		dataType: int64
		sourceColumn: [DunningLevel]

	partition Fact_AR = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("C:/tmp/PowerBi-Codex-Plugin/outputs/powerbi-industrial-demo/powerbi_industrial_demo_data.xlsx"), null, true),
			    Raw = Source{[Item="Fact_AR", Kind="Sheet"]}[Data],
			    PromotedHeaders = Table.PromoteHeaders(Raw, [PromoteAllScalars = true]),
			    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"InvoiceID", type text}, {"CustomerID", type text}, {"DueDate", type date}, {"OpenAmount", type number}, {"PaymentDate", type date}, {"DisputeFlag", type logical}, {"DunningLevel", Int64.Type}}, "en-US")
			in
			    ChangedType
