-- Maintain2Operate generated DAX measure catalog
-- Demo value column: ProcessCases[DowntimeCost]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total DowntimeCost = SUM('ProcessCases'[DowntimeCost])

PM Compliance = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Downtime Cost = AVERAGE('ProcessCases'[ActualCycleDays])
MTBF = SUM('ProcessCases'[DowntimeCost])
MTTR = SUM('ProcessCases'[DowntimeCost])
Maintenance Backlog = SUM('ProcessCases'[DowntimeCost])
