-- Record2Report generated DAX measure catalog
-- Demo value column: ProcessCases[FinancialImpact]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total FinancialImpact = SUM('ProcessCases'[FinancialImpact])

Close Cycle Time = AVERAGE('ProcessCases'[ActualCycleDays])
Late Posting Count = COUNTROWS('ProcessCases')
Reconciliation Breaks = SUM('ProcessCases'[FinancialImpact])
Journal Error Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Audit Finding Count = COUNTROWS('ProcessCases')
