-- Quote2Contract generated DAX measure catalog
-- Demo value column: ProcessCases[ContractValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total ContractValue = SUM('ProcessCases'[ContractValue])

Contract Cycle Time = AVERAGE('ProcessCases'[ActualCycleDays])
Redline Loops = COUNTROWS('ProcessCases')
Term Deviation Count = COUNTROWS('ProcessCases')
Value At Risk = AVERAGE('ProcessCases'[RiskScore])
Signature Aging = AVERAGE('ProcessCases'[ActualCycleDays])
