-- Design2Cost / Design2Source generated DAX measure catalog
-- Demo value column: ProcessCases[CostVariance]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total CostVariance = SUM('ProcessCases'[CostVariance])

Target Cost Variance = SUM('ProcessCases'[CostVariance])
Part Reuse Pct = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Single-Source Exposure = SUM('ProcessCases'[CostVariance])
Sourcing Readiness = SUM('ProcessCases'[CostVariance])
Engineering Cost Risk = AVERAGE('ProcessCases'[RiskScore])
