table ProcessKpiSnapshots
	column ProcessID
		dataType: string
		sourceColumn: [ProcessID]

	column ProcessName
		dataType: string
		sourceColumn: [ProcessName]

	column Period
		dataType: dateTime
		sourceColumn: [Period]

	column KPIName
		dataType: string
		sourceColumn: [KPIName]

	column ActualValue
		dataType: double
		sourceColumn: [ActualValue]

	column TargetValue
		dataType: double
		sourceColumn: [TargetValue]

	column Tolerance
		dataType: double
		sourceColumn: [Tolerance]

	column Status
		dataType: string
		sourceColumn: [Status]

	column OwnerRole
		dataType: string
		sourceColumn: [OwnerRole]

	column SourceSystems
		dataType: string
		sourceColumn: [SourceSystems]

	partition ProcessKpiSnapshots = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:/tmp/PowerBi-Codex-Plugin/outputs/industry-demo-data/lead2order/kpi_snapshots.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
			    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"ProcessID", type text}, {"ProcessName", type text}, {"Period", type date}, {"KPIName", type text}, {"ActualValue", type number}, {"TargetValue", type number}, {"Tolerance", type number}, {"Status", type text}, {"OwnerRole", type text}, {"SourceSystems", type text}}, "en-US")
			in
			    ChangedType
