-- Procure2Pay generated DAX measure catalog
-- Demo value column: ProcessCases[SpendValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total SpendValue = SUM('ProcessCases'[SpendValue])

Spend Value = SUM('ProcessCases'[SpendValue])
Invoice Block Value = SUM('ProcessCases'[SpendValue])
GR/IR Aging = AVERAGE('ProcessCases'[ActualCycleDays])
Discount Capture Pct = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Supplier On-Time Pct = AVERAGE('ProcessCases'[ActualCycleDays])
