-- Nonconformance2Disposition generated DAX measure catalog
-- Demo value column: ProcessCases[BlockedValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total BlockedValue = SUM('ProcessCases'[BlockedValue])

Defect Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Blocked Stock Value = SUM('ProcessCases'[BlockedValue])
Rework Cost = SUM('ProcessCases'[BlockedValue])
Supplier PPM = SUM('ProcessCases'[BlockedValue])
Disposition Aging = AVERAGE('ProcessCases'[ActualCycleDays])
