-- Order2Cash generated DAX measure catalog
-- Demo value column: ProcessCases[OrderValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total OrderValue = SUM('ProcessCases'[OrderValue])

Order Value = SUM('ProcessCases'[OrderValue])
Backlog Value = SUM('ProcessCases'[OrderValue])
OTIF Pct = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Billing Block Value = SUM('ProcessCases'[OrderValue])
Open AR = SUM('ProcessCases'[OrderValue])
DSO = SUM('ProcessCases'[OrderValue])
