-- Issue2Resolution generated DAX measure catalog
-- Demo value column: ProcessCases[IssueCost]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total IssueCost = SUM('ProcessCases'[IssueCost])

Issue Aging = AVERAGE('ProcessCases'[ActualCycleDays])
SLA Breach Pct = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Warranty Cost = SUM('ProcessCases'[IssueCost])
Repeat Issue Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Corrective Action Aging = AVERAGE('ProcessCases'[ActualCycleDays])
