table ProcessCases
	column ProcessID
		dataType: string
		sourceColumn: [ProcessID]

	column ProcessName
		dataType: string
		sourceColumn: [ProcessName]

	column CaseID
		dataType: string
		sourceColumn: [CaseID]

	column CaseName
		dataType: string
		sourceColumn: [CaseName]

	column Domain
		dataType: string
		sourceColumn: [Domain]

	column OwnerRole
		dataType: string
		sourceColumn: [OwnerRole]

	column OwnerName
		dataType: string
		sourceColumn: [OwnerName]

	column Region
		dataType: string
		sourceColumn: [Region]

	column PlantID
		dataType: string
		sourceColumn: [PlantID]

	column BusinessPartner
		dataType: string
		sourceColumn: [BusinessPartner]

	column CurrentStage
		dataType: string
		sourceColumn: [CurrentStage]

	column StartDate
		dataType: dateTime
		sourceColumn: [StartDate]

	column TargetDate
		dataType: dateTime
		sourceColumn: [TargetDate]

	column ActualOrForecastDate
		dataType: dateTime
		sourceColumn: [ActualOrForecastDate]

	column TargetCycleDays
		dataType: int64
		sourceColumn: [TargetCycleDays]

	column ActualCycleDays
		dataType: int64
		sourceColumn: [ActualCycleDays]

	column SlaBreached
		dataType: boolean
		sourceColumn: [SlaBreached]

	column RootCause
		dataType: string
		sourceColumn: [RootCause]

	column CommitmentValue
		dataType: double
		sourceColumn: [CommitmentValue]

	column RiskScore
		dataType: int64
		sourceColumn: [RiskScore]

	column ActionRequired
		dataType: boolean
		sourceColumn: [ActionRequired]

	measure 'Case Count' =
		COUNTROWS('ProcessCases')

	measure 'SLA Breach Count' =
		CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())

	measure 'Action Required Count' =
		CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())

	partition ProcessCases = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:/tmp/PowerBi-Codex-Plugin/outputs/industry-demo-data/make_strategy/cases.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
			    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
			    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"ProcessID", type text}, {"ProcessName", type text}, {"CaseID", type text}, {"CaseName", type text}, {"Domain", type text}, {"OwnerRole", type text}, {"OwnerName", type text}, {"Region", type text}, {"PlantID", type text}, {"BusinessPartner", type text}, {"CurrentStage", type text}, {"StartDate", type date}, {"TargetDate", type date}, {"ActualOrForecastDate", type date}, {"TargetCycleDays", Int64.Type}, {"ActualCycleDays", Int64.Type}, {"SlaBreached", type logical}, {"RootCause", type text}, {"CommitmentValue", type number}, {"RiskScore", Int64.Type}, {"ActionRequired", type logical}}, "en-US")
			in
			    ChangedType
