-- Control2Evidence generated DAX measure catalog
-- Demo value column: ProcessCases[ControlRiskValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total ControlRiskValue = SUM('ProcessCases'[ControlRiskValue])

Control Effectiveness = SUM('ProcessCases'[ControlRiskValue])
Evidence Coverage = SUM('ProcessCases'[ControlRiskValue])
SoD Violations = SUM('ProcessCases'[ControlRiskValue])
Remediation Aging = AVERAGE('ProcessCases'[ActualCycleDays])
Audit Gap Count = COUNTROWS('ProcessCases')
