-- Incident2Action generated DAX measure catalog
-- Demo value column: ProcessCases[RiskValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total RiskValue = SUM('ProcessCases'[RiskValue])

Incident Rate = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Severity Score = AVERAGE('ProcessCases'[RiskScore])
Response Time = AVERAGE('ProcessCases'[ActualCycleDays])
Overdue Actions = SUM('ProcessCases'[RiskValue])
Risk Exposure = AVERAGE('ProcessCases'[RiskScore])
