-- Forecast2Plan generated DAX measure catalog
-- Demo value column: ProcessCases[ForecastValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total ForecastValue = SUM('ProcessCases'[ForecastValue])

Forecast Accuracy = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Forecast Bias = SUM('ProcessCases'[ForecastValue])
S&OP Gap = SUM('ProcessCases'[ForecastValue])
Inventory Target Gap = SUM('ProcessCases'[ForecastValue])
Demand Volatility = SUM('ProcessCases'[ForecastValue])
