-- Source2Contract generated DAX measure catalog
-- Demo value column: ProcessCases[ContractValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total ContractValue = SUM('ProcessCases'[ContractValue])

Sourcing Cycle Time = AVERAGE('ProcessCases'[ActualCycleDays])
Contract Value At Risk = AVERAGE('ProcessCases'[RiskScore])
Supplier Compliance Pct = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Legal Loop Count = COUNTROWS('ProcessCases')
Savings Value = SUM('ProcessCases'[ContractValue])
