table Fact_SalesOrders
	lineageTag: bc4e3e91-4b7f-5cf5-bd4b-cf5910bc287f

	column SalesOrderID
		dataType: string
		sourceColumn: [SalesOrderID]

	column QuoteID
		dataType: string
		sourceColumn: [QuoteID]

	column CustomerID
		dataType: string
		sourceColumn: [CustomerID]

	column ProductID
		dataType: string
		sourceColumn: [ProductID]

	column PlantID
		dataType: string
		sourceColumn: [PlantID]

	column OrderDate
		dataType: dateTime
		sourceColumn: [OrderDate]

	column RequestedDate
		dataType: dateTime
		sourceColumn: [RequestedDate]

	column ConfirmedDate
		dataType: dateTime
		sourceColumn: [ConfirmedDate]

	column OrderQty
		dataType: int64
		sourceColumn: [OrderQty]

	column NetPrice
		dataType: double
		sourceColumn: [NetPrice]

	column OrderValue
		dataType: double
		sourceColumn: [OrderValue]

	column Status
		dataType: string
		sourceColumn: [Status]

	column ATPStatus
		dataType: string
		sourceColumn: [ATPStatus]

	partition Fact_SalesOrders = calculated
		mode: import
		source =
			DATATABLE(
				"SalesOrderID", STRING,
				"QuoteID", STRING,
				"CustomerID", STRING,
				"ProductID", STRING,
				"PlantID", STRING,
				"OrderDate", DATETIME,
				"RequestedDate", DATETIME,
				"ConfirmedDate", DATETIME,
				"OrderQty", INTEGER,
				"NetPrice", DOUBLE,
				"OrderValue", DOUBLE,
				"Status", STRING,
				"ATPStatus", STRING,
				{
					{ "SO000001", "Q00030", "C0014", "P0033", "SG10", dt"2025-07-06", dt"2025-07-31", dt"2025-08-02", 68, 898.12, 61072.16, "Open", "Partial" },
					{ "SO000002", "Q00100", "C0005", "P0033", "DE20", dt"2025-09-25", dt"2025-10-06", dt"2025-10-17", 34, 937.9, 31888.6, "Open", "Partial" },
					{ "SO000003", "Q00001", "C0046", "P0002", "DE10", dt"2025-08-15", dt"2025-09-18", dt"2025-09-27", 27, 9205.56, 248550.12, "Cancelled", "Partial" },
					{ "SO000004", "Q00078", "C0010", "P0010", "DE10", dt"2025-11-17", dt"2025-11-28", dt"2026-01-26", 53, 7392.27, 391790.31, "Open", "Confirmed" },
					{ "SO000005", "Q00045", "C0043", "P0028", "SG10", dt"2025-10-12", dt"2025-11-13", dt"2025-12-12", 47, 8515.46, 400226.62, "Open", "Confirmed" },
					{ "SO000006", "Q00042", "C0055", "P0031", "US10", dt"2026-03-01", dt"2026-04-03", dt"2026-04-30", 12, 7082.3, 84987.6, "Partially Delivered", "Confirmed" },
					{ "SO000007", "Q00088", "C0034", "P0006", "DE20", dt"2026-02-07", dt"2026-02-25", dt"2026-02-25", 32, 2515.53, 80496.96, "Open", "Manual Review" },
					{ "SO000008", "Q00039", "C0010", "P0031", "DE10", dt"2025-11-02", dt"2025-11-16", dt"2025-11-27", 12, 7856.2, 94274.4, "Delivered", "Shortage" },
					{ "SO000009", "Q00027", "C0017", "P0004", "DE10", dt"2025-09-02", dt"2025-09-09", dt"2025-09-13", 46, 7514.95, 345687.7, "Open", "Partial" },
					{ "SO000010", "Q00099", "C0018", "P0008", "US10", dt"2026-01-07", dt"2026-02-03", dt"2026-02-15", 74, 1352.6, 100092.4, "Cancelled", "Shortage" },
					{ "SO000011", "Q00096", "C0027", "P0031", "DE10", dt"2025-04-20", dt"2025-06-09", dt"2025-05-31", 80, 7526.2, 602096.0, "Open", "Shortage" },
					{ "SO000012", "Q00078", "C0010", "P0016", "DE10", dt"2025-05-03", dt"2025-06-08", dt"2025-05-15", 8, 5303.46, 42427.68, "Open", "Partial" },
					{ "SO000013", "Q00004", "C0029", "P0004", "DE10", dt"2025-10-31", dt"2025-11-15", dt"2026-01-01", 12, 8003.11, 96037.32, "Cancelled", "Shortage" },
					{ "SO000014", "Q00014", "C0012", "P0031", "SG10", dt"2026-03-01", dt"2026-04-12", dt"2026-05-09", 52, 6926.36, 360170.72, "Open", "Confirmed" },
					{ "SO000015", "Q00013", "C0002", "P0017", "DE10", dt"2025-08-10", dt"2025-09-13", dt"2025-08-30", 32, 722.76, 23128.32, "Cancelled", "Partial" },
					{ "SO000016", "Q00043", "C0013", "P0036", "DE10", dt"2025-02-17", dt"2025-03-26", dt"2025-03-09", 10, 7335.23, 73352.3, "Open", "Manual Review" },
					{ "SO000017", "Q00081", "C0019", "P0023", "DE10", dt"2025-10-22", dt"2025-11-19", dt"2025-12-18", 21, 1859.3, 39045.3, "Delivered", "Confirmed" },
					{ "SO000018", "Q00049", "C0050", "P0009", "DE20", dt"2025-08-31", dt"2025-09-20", dt"2025-10-06", 35, 1555.99, 54459.65, "Delivered", "Manual Review" },
					{ "SO000019", "Q00097", "C0022", "P0035", "SG10", dt"2025-05-14", dt"2025-06-01", dt"2025-06-19", 44, 710.03, 31241.32, "Delivered", "Confirmed" },
					{ "SO000020", "Q00071", "C0009", "P0023", "DE10", dt"2025-07-17", dt"2025-08-06", dt"2025-09-22", 23, 2168.31, 49871.13, "Partially Delivered", "Partial" },
					{ "SO000021", "Q00095", "C0057", "P0032", "SG10", dt"2025-05-30", dt"2025-06-10", dt"2025-07-03", 23, 3879.31, 89224.13, "Open", "Shortage" },
					{ "SO000022", "Q00058", "C0018", "P0005", "SG10", dt"2026-01-14", dt"2026-02-13", dt"2026-03-11", 80, 4870.5, 389640.0, "Partially Delivered", "Partial" },
					{ "SO000023", "Q00096", "C0027", "P0019", "DE10", dt"2025-07-27", dt"2025-08-19", dt"2025-09-18", 46, 1556.62, 71604.52, "Delivered", "Confirmed" },
					{ "SO000024", "Q00059", "C0047", "P0017", "SG10", dt"2025-09-24", dt"2025-11-17", dt"2025-10-28", 40, 727.99, 29119.6, "Open", "Confirmed" },
					{ "SO000025", "Q00050", "C0004", "P0017", "DE20", dt"2025-07-09", dt"2025-08-11", dt"2025-09-02", 70, 554.8, 38836.0, "Cancelled", "Manual Review" },
					{ "SO000026", "Q00001", "C0046", "P0031", "DE20", dt"2026-02-04", dt"2026-03-16", dt"2026-02-22", 43, 7412.23, 318725.89, "Delivered", "Partial" },
					{ "SO000027", "Q00049", "C0050", "P0019", "DE10", dt"2025-05-27", dt"2025-06-05", dt"2025-07-18", 36, 1482.02, 53352.72, "Open", "Partial" },
					{ "SO000028", "Q00068", "C0052", "P0008", "DE10", dt"2025-05-20", dt"2025-07-18", dt"2025-06-07", 37, 1512.08, 55946.96, "Partially Delivered", "Confirmed" },
					{ "SO000029", "Q00040", "C0057", "P0030", "SG10", dt"2026-01-15", dt"2026-03-02", dt"2026-02-04", 67, 2396.02, 160533.34, "Delivered", "Shortage" },
					{ "SO000030", "Q00095", "C0057", "P0030", "US10", dt"2025-03-01", dt"2025-04-05", dt"2025-04-30", 17, 2364.78, 40201.26, "Delivered", "Manual Review" },
					{ "SO000031", "Q00074", "C0004", "P0030", "DE20", dt"2025-07-16", dt"2025-07-25", dt"2025-09-07", 53, 2288.56, 121293.68, "Cancelled", "Confirmed" },
					{ "SO000032", "Q00055", "C0012", "P0023", "US10", dt"2025-04-14", dt"2025-05-14", dt"2025-06-15", 15, 2127.55, 31913.25, "Partially Delivered", "Shortage" },
					{ "SO000033", "Q00043", "C0013", "P0031", "DE20", dt"2025-09-03", dt"2025-09-29", dt"2025-10-11", 10, 6768.57, 67685.7, "Partially Delivered", "Shortage" },
					{ "SO000034", "Q00079", "C0036", "P0016", "DE10", dt"2025-03-07", dt"2025-03-30", dt"2025-04-30", 20, 6057.35, 121147.0, "Delivered", "Shortage" },
					{ "SO000035", "Q00023", "C0052", "P0013", "SG10", dt"2026-03-15", dt"2026-03-30", dt"2026-04-06", 77, 1448.78, 111556.06, "Cancelled", "Manual Review" },
					{ "SO000036", "Q00042", "C0055", "P0026", "SG10", dt"2025-08-17", dt"2025-08-28", dt"2025-09-05", 5, 6673.38, 33366.9, "Delivered", "Partial" },
					{ "SO000037", "Q00100", "C0005", "P0035", "SG10", dt"2025-12-10", dt"2025-12-20", dt"2025-12-25", 66, 738.98, 48772.68, "Delivered", "Manual Review" },
					{ "SO000038", "Q00026", "C0011", "P0001", "SG10", dt"2025-10-09", dt"2025-11-08", dt"2025-11-02", 36, 729.79, 26272.44, "Partially Delivered", "Partial" },
					{ "SO000039", "Q00040", "C0057", "P0002", "DE10", dt"2025-11-12", dt"2025-12-29", dt"2025-11-28", 12, 8829.54, 105954.48, "Partially Delivered", "Partial" },
					{ "SO000040", "Q00011", "C0045", "P0030", "DE20", dt"2025-07-21", dt"2025-08-21", dt"2025-08-13", 38, 2246.13, 85352.94, "Open", "Partial" },
					{ "SO000041", "Q00077", "C0019", "P0015", "US10", dt"2025-03-15", dt"2025-05-07", dt"2025-04-18", 20, 1581.93, 31638.6, "Open", "Partial" },
					{ "SO000042", "Q00082", "C0045", "P0021", "DE20", dt"2025-04-27", dt"2025-05-28", dt"2025-06-28", 35, 4854.6, 169911.0, "Open", "Manual Review" },
					{ "SO000043", "Q00075", "C0059", "P0003", "DE10", dt"2025-05-22", dt"2025-06-01", dt"2025-06-22", 78, 6078.61, 474131.58, "Delivered", "Manual Review" },
					{ "SO000044", "Q00035", "C0056", "P0015", "SG10", dt"2025-02-24", dt"2025-03-06", dt"2025-04-27", 3, 1371.17, 4113.51, "Cancelled", "Confirmed" },
					{ "SO000045", "Q00011", "C0045", "P0029", "SG10", dt"2025-02-27", dt"2025-04-01", dt"2025-03-10", 13, 1607.45, 20896.85, "Partially Delivered", "Manual Review" },
					{ "SO000046", "Q00032", "C0028", "P0009", "DE10", dt"2025-08-23", dt"2025-10-02", dt"2025-10-01", 26, 1641.87, 42688.62, "Open", "Partial" },
					{ "SO000047", "Q00101", "C0042", "P0010", "US10", dt"2025-09-07", dt"2025-09-21", dt"2025-10-20", 2, 8221.99, 16443.98, "Open", "Shortage" },
					{ "SO000048", "Q00033", "C0018", "P0029", "US10", dt"2025-02-15", dt"2025-03-28", dt"2025-03-09", 24, 1599.15, 38379.6, "Cancelled", "Shortage" },
					{ "SO000049", "Q00030", "C0014", "P0008", "SG10", dt"2026-03-22", dt"2026-03-30", dt"2026-04-02", 69, 1504.37, 103801.53, "Delivered", "Manual Review" },
					{ "SO000050", "Q00101", "C0042", "P0023", "DE20", dt"2026-02-12", dt"2026-02-27", dt"2026-04-16", 5, 1929.06, 9645.3, "Open", "Manual Review" },
					{ "SO000051", "Q00098", "C0045", "P0006", "SG10", dt"2026-01-31", dt"2026-03-26", dt"2026-03-19", 63, 3080.04, 194042.52, "Open", "Shortage" },
					{ "SO000052", "Q00065", "C0018", "P0026", "DE20", dt"2025-06-05", dt"2025-06-19", dt"2025-08-08", 10, 6820.73, 68207.3, "Open", "Manual Review" },
					{ "SO000053", "Q00058", "C0018", "P0011", "DE10", dt"2025-11-25", dt"2025-12-05", dt"2026-01-11", 45, 3957.24, 178075.8, "Open", "Shortage" },
					{ "SO000054", "Q00085", "C0053", "P0036", "DE20", dt"2026-02-21", dt"2026-03-24", dt"2026-03-09", 18, 7313.47, 131642.46, "Delivered", "Confirmed" },
					{ "SO000055", "Q00027", "C0017", "P0032", "US10", dt"2025-09-07", dt"2025-10-12", dt"2025-10-10", 49, 3448.74, 168988.26, "Cancelled", "Confirmed" },
					{ "SO000056", "Q00051", "C0013", "P0015", "SG10", dt"2026-04-04", dt"2026-05-12", dt"2026-06-06", 44, 1266.84, 55740.96, "Open", "Confirmed" },
					{ "SO000057", "Q00101", "C0042", "P0033", "DE10", dt"2026-02-14", dt"2026-04-10", dt"2026-03-19", 56, 924.01, 51744.56, "Cancelled", "Confirmed" },
					{ "SO000058", "Q00014", "C0012", "P0007", "US10", dt"2025-04-29", dt"2025-05-08", dt"2025-05-23", 39, 3328.37, 129806.43, "Open", "Confirmed" },
					{ "SO000059", "Q00081", "C0019", "P0034", "US10", dt"2025-06-08", dt"2025-07-09", dt"2025-07-20", 76, 3299.36, 250751.36, "Open", "Manual Review" },
					{ "SO000060", "Q00028", "C0028", "P0035", "DE10", dt"2025-08-16", dt"2025-10-02", dt"2025-10-16", 17, 811.73, 13799.41, "Open", "Manual Review" },
					{ "SO000061", "Q00017", "C0032", "P0034", "SG10", dt"2025-11-08", dt"2025-12-05", dt"2025-11-22", 24, 3895.5, 93492.0, "Open", "Partial" },
					{ "SO000062", "Q00049", "C0050", "P0015", "DE20", dt"2026-02-06", dt"2026-03-10", dt"2026-04-04", 48, 1512.57, 72603.36, "Open", "Shortage" },
					{ "SO000063", "Q00016", "C0004", "P0026", "US10", dt"2026-01-30", dt"2026-02-11", dt"2026-02-27", 33, 5949.48, 196332.84, "Open", "Manual Review" },
					{ "SO000064", "Q00031", "C0036", "P0002", "DE20", dt"2025-03-30", dt"2025-05-03", dt"2025-06-07", 33, 7013.26, 231437.58, "Open", "Partial" },
					{ "SO000065", "Q00063", "C0006", "P0023", "US10", dt"2026-03-20", dt"2026-05-01", dt"2026-03-31", 41, 2288.34, 93821.94, "Cancelled", "Manual Review" },
					{ "SO000066", "Q00101", "C0042", "P0029", "SG10", dt"2025-10-01", dt"2025-11-20", dt"2025-11-23", 69, 1951.85, 134677.65, "Open", "Partial" },
					{ "SO000067", "Q00067", "C0050", "P0028", "US10", dt"2025-08-23", dt"2025-09-24", dt"2025-09-30", 7, 7015.82, 49110.74, "Open", "Partial" },
					{ "SO000068", "Q00010", "C0034", "P0029", "DE10", dt"2025-11-17", dt"2025-12-07", dt"2026-01-06", 50, 1849.45, 92472.5, "Open", "Manual Review" },
					{ "SO000069", "Q00023", "C0052", "P0031", "US10", dt"2025-08-11", dt"2025-09-27", dt"2025-08-22", 3, 7436.32, 22308.96, "Open", "Confirmed" },
					{ "SO000070", "Q00093", "C0048", "P0028", "DE20", dt"2025-02-17", dt"2025-02-28", dt"2025-04-14", 24, 8095.68, 194296.32, "Open", "Shortage" },
					{ "SO000071", "Q00044", "C0054", "P0005", "DE20", dt"2025-10-27", dt"2025-12-15", dt"2025-11-22", 67, 5217.27, 349557.09, "Partially Delivered", "Shortage" },
					{ "SO000072", "Q00078", "C0010", "P0011", "SG10", dt"2025-02-18", dt"2025-04-06", dt"2025-03-16", 55, 3467.0, 190685.0, "Delivered", "Manual Review" },
					{ "SO000073", "Q00022", "C0049", "P0007", "US10", dt"2026-03-07", dt"2026-04-24", dt"2026-05-08", 66, 3098.93, 204529.38, "Open", "Shortage" },
					{ "SO000074", "Q00043", "C0013", "P0013", "US10", dt"2025-07-16", dt"2025-08-28", dt"2025-09-12", 25, 1454.43, 36360.75, "Delivered", "Manual Review" },
					{ "SO000075", "Q00007", "C0032", "P0001", "US10", dt"2026-01-16", dt"2026-02-16", dt"2026-02-20", 53, 798.3, 42309.9, "Open", "Shortage" },
					{ "SO000076", "Q00089", "C0058", "P0032", "DE20", dt"2025-11-30", dt"2025-12-25", dt"2026-02-05", 35, 4270.3, 149460.5, "Partially Delivered", "Partial" },
					{ "SO000077", "Q00017", "C0032", "P0030", "DE20", dt"2025-07-06", dt"2025-07-25", dt"2025-08-04", 50, 2330.57, 116528.5, "Cancelled", "Shortage" },
					{ "SO000078", "Q00089", "C0058", "P0002", "DE10", dt"2025-10-10", dt"2025-10-24", dt"2025-10-29", 71, 8419.66, 597795.86, "Delivered", "Partial" },
					{ "SO000079", "Q00025", "C0046", "P0035", "DE10", dt"2025-04-22", dt"2025-05-23", dt"2025-05-17", 10, 793.16, 7931.6, "Open", "Partial" },
					{ "SO000080", "Q00045", "C0043", "P0017", "DE10", dt"2026-02-08", dt"2026-03-03", dt"2026-04-02", 3, 617.54, 1852.62, "Open", "Partial" },
					{ "SO000081", "Q00072", "C0045", "P0005", "SG10", dt"2025-08-16", dt"2025-10-12", dt"2025-10-19", 62, 5566.49, 345122.38, "Open", "Partial" },
					{ "SO000082", "Q00034", "C0040", "P0028", "DE20", dt"2026-04-03", dt"2026-04-21", dt"2026-06-12", 32, 6758.83, 216282.56, "Partially Delivered", "Shortage" },
					{ "SO000083", "Q00015", "C0006", "P0004", "US10", dt"2025-11-02", dt"2025-12-24", dt"2025-12-31", 68, 7755.8, 527394.4, "Delivered", "Manual Review" },
					{ "SO000084", "Q00042", "C0055", "P0012", "SG10", dt"2026-01-03", dt"2026-02-15", dt"2026-01-27", 61, 6007.76, 366473.36, "Cancelled", "Partial" },
					{ "SO000085", "Q00008", "C0014", "P0013", "DE10", dt"2026-01-03", dt"2026-02-16", dt"2026-03-03", 74, 1229.67, 90995.58, "Delivered", "Manual Review" },
					{ "SO000086", "Q00028", "C0028", "P0017", "DE10", dt"2026-03-14", dt"2026-04-12", dt"2026-03-29", 76, 595.28, 45241.28, "Open", "Partial" },
					{ "SO000087", "Q00063", "C0006", "P0029", "DE10", dt"2025-08-05", dt"2025-09-28", dt"2025-08-20", 6, 1601.14, 9606.84, "Open", "Partial" },
					{ "SO000088", "Q00038", "C0049", "P0004", "US10", dt"2025-03-26", dt"2025-04-20", dt"2025-04-05", 30, 6529.12, 195873.6, "Delivered", "Partial" },
					{ "SO000089", "Q00049", "C0050", "P0025", "DE20", dt"2025-08-21", dt"2025-09-05", dt"2025-08-31", 72, 1189.38, 85635.36, "Open", "Confirmed" },
					{ "SO000090", "Q00084", "C0009", "P0019", "DE10", dt"2025-07-22", dt"2025-09-02", dt"2025-08-08", 24, 1812.71, 43505.04, "Delivered", "Partial" },
					{ "SO000091", "Q00026", "C0011", "P0024", "DE20", dt"2025-08-26", dt"2025-09-05", dt"2025-09-25", 22, 6067.18, 133477.96, "Delivered", "Shortage" },
					{ "SO000092", "Q00055", "C0012", "P0011", "DE10", dt"2025-07-29", dt"2025-08-28", dt"2025-08-29", 9, 3344.32, 30098.88, "Cancelled", "Partial" },
					{ "SO000093", "Q00027", "C0017", "P0027", "DE10", dt"2025-08-30", dt"2025-10-24", dt"2025-09-21", 49, 4591.2, 224968.8, "Open", "Manual Review" },
					{ "SO000094", "Q00017", "C0032", "P0004", "DE10", dt"2025-11-11", dt"2025-12-05", dt"2025-12-16", 29, 8222.84, 238462.36, "Partially Delivered", "Confirmed" },
					{ "SO000095", "Q00014", "C0012", "P0029", "SG10", dt"2025-03-19", dt"2025-05-11", dt"2025-04-15", 70, 1782.28, 124759.6, "Open", "Partial" },
					{ "SO000096", "Q00020", "C0021", "P0025", "SG10", dt"2025-09-11", dt"2025-11-10", dt"2025-11-03", 12, 1136.44, 13637.28, "Open", "Shortage" },
					{ "SO000097", "Q00093", "C0048", "P0001", "SG10", dt"2025-08-13", dt"2025-10-08", dt"2025-10-18", 78, 868.75, 67762.5, "Open", "Manual Review" },
					{ "SO000098", "Q00025", "C0046", "P0007", "US10", dt"2025-03-30", dt"2025-05-06", dt"2025-05-15", 16, 3713.43, 59414.88, "Delivered", "Confirmed" },
					{ "SO000099", "Q00055", "C0012", "P0017", "DE10", dt"2025-07-21", dt"2025-08-27", dt"2025-09-15", 74, 632.4, 46797.6, "Open", "Manual Review" },
					{ "SO000100", "Q00023", "C0052", "P0024", "DE20", dt"2025-04-25", dt"2025-06-18", dt"2025-06-15", 56, 7434.05, 416306.8, "Open", "Manual Review" },
					{ "SO000101", "Q00084", "C0009", "P0006", "US10", dt"2026-04-06", dt"2026-05-08", dt"2026-06-05", 1, 2717.24, 2717.24, "Cancelled", "Confirmed" },
					{ "SO000102", "Q00091", "C0046", "P0017", "SG10", dt"2025-04-22", dt"2025-05-11", dt"2025-06-03", 54, 705.15, 38078.1, "Partially Delivered", "Shortage" },
					{ "SO000103", "Q00038", "C0049", "P0033", "SG10", dt"2025-03-30", dt"2025-04-25", dt"2025-05-31", 77, 796.11, 61300.47, "Delivered", "Shortage" },
					{ "SO000104", "Q00021", "C0031", "P0003", "US10", dt"2025-12-14", dt"2026-01-17", dt"2026-01-28", 51, 6584.16, 335792.16, "Open", "Shortage" },
					{ "SO000105", "Q00097", "C0022", "P0002", "US10", dt"2025-12-24", dt"2026-01-06", dt"2026-02-23", 66, 7749.6, 511473.6, "Partially Delivered", "Partial" },
					{ "SO000106", "Q00021", "C0031", "P0001", "US10", dt"2025-02-18", dt"2025-03-20", dt"2025-04-18", 47, 902.46, 42415.62, "Delivered", "Manual Review" },
					{ "SO000107", "Q00045", "C0043", "P0023", "DE20", dt"2025-05-24", dt"2025-07-20", dt"2025-07-17", 69, 2120.27, 146298.63, "Delivered", "Manual Review" },
					{ "SO000108", "Q00061", "C0053", "P0014", "DE20", dt"2025-10-23", dt"2025-12-21", dt"2025-12-03", 57, 422.26, 24068.82, "Cancelled", "Confirmed" },
					{ "SO000109", "Q00022", "C0049", "P0024", "SG10", dt"2026-02-01", dt"2026-02-15", dt"2026-03-14", 70, 7173.45, 502141.5, "Delivered", "Confirmed" },
					{ "SO000110", "Q00016", "C0004", "P0034", "DE10", dt"2025-12-09", dt"2025-12-30", dt"2025-12-22", 31, 3158.54, 97914.74, "Open", "Manual Review" },
					{ "SO000111", "Q00055", "C0012", "P0033", "DE10", dt"2026-03-08", dt"2026-03-31", dt"2026-03-19", 62, 773.34, 47947.08, "Partially Delivered", "Shortage" },
					{ "SO000112", "Q00043", "C0013", "P0002", "US10", dt"2025-05-27", dt"2025-06-21", dt"2025-08-04", 22, 7986.48, 175702.56, "Delivered", "Confirmed" },
					{ "SO000113", "Q00070", "C0025", "P0028", "DE10", dt"2026-03-14", dt"2026-03-31", dt"2026-04-14", 8, 8608.76, 68870.08, "Open", "Partial" },
					{ "SO000114", "Q00070", "C0025", "P0019", "US10", dt"2025-03-18", dt"2025-03-30", dt"2025-04-20", 43, 1652.46, 71055.78, "Cancelled", "Manual Review" },
					{ "SO000115", "Q00034", "C0040", "P0022", "SG10", dt"2025-03-13", dt"2025-05-07", dt"2025-04-27", 8, 2737.65, 21901.2, "Partially Delivered", "Partial" },
					{ "SO000116", "Q00008", "C0014", "P0009", "DE10", dt"2026-02-14", dt"2026-04-02", dt"2026-03-13", 53, 1349.7, 71534.1, "Partially Delivered", "Partial" },
					{ "SO000117", "Q00077", "C0019", "P0013", "SG10", dt"2026-03-04", dt"2026-04-10", dt"2026-04-02", 19, 1362.51, 25887.69, "Partially Delivered", "Shortage" },
					{ "SO000118", "Q00100", "C0005", "P0019", "DE20", dt"2026-04-01", dt"2026-05-18", dt"2026-06-08", 22, 1507.35, 33161.7, "Open", "Confirmed" },
					{ "SO000119", "Q00005", "C0051", "P0015", "SG10", dt"2025-11-27", dt"2026-01-26", dt"2025-12-18", 46, 1552.42, 71411.32, "Partially Delivered", "Shortage" },
					{ "SO000120", "Q00064", "C0014", "P0036", "DE10", dt"2025-05-15", dt"2025-06-04", dt"2025-06-01", 79, 6113.27, 482948.33, "Open", "Confirmed" },
					{ "SO000121", "Q00090", "C0017", "P0004", "SG10", dt"2025-02-22", dt"2025-03-13", dt"2025-03-20", 12, 6852.02, 82224.24, "Open", "Confirmed" },
					{ "SO000122", "Q00011", "C0045", "P0036", "DE10", dt"2025-05-18", dt"2025-06-19", dt"2025-06-28", 7, 5580.12, 39060.84, "Partially Delivered", "Confirmed" },
					{ "SO000123", "Q00002", "C0036", "P0008", "DE10", dt"2025-07-08", dt"2025-08-08", dt"2025-07-31", 30, 1662.35, 49870.5, "Delivered", "Shortage" },
					{ "SO000124", "Q00035", "C0056", "P0012", "DE10", dt"2025-12-05", dt"2025-12-23", dt"2025-12-18", 55, 6852.14, 376867.7, "Open", "Manual Review" },
					{ "SO000125", "Q00032", "C0028", "P0012", "US10", dt"2025-12-25", dt"2026-02-07", dt"2026-02-01", 16, 5304.11, 84865.76, "Delivered", "Partial" },
					{ "SO000126", "Q00093", "C0048", "P0007", "US10", dt"2025-02-28", dt"2025-04-17", dt"2025-05-07", 54, 3794.95, 204927.3, "Cancelled", "Confirmed" },
					{ "SO000127", "Q00101", "C0042", "P0035", "SG10", dt"2025-12-21", dt"2026-02-13", dt"2026-02-07", 23, 763.69, 17564.87, "Partially Delivered", "Confirmed" },
					{ "SO000128", "Q00048", "C0023", "P0012", "US10", dt"2025-04-23", dt"2025-05-04", dt"2025-05-25", 36, 5471.62, 196978.32, "Delivered", "Manual Review" },
					{ "SO000129", "Q00057", "C0005", "P0004", "DE20", dt"2026-03-16", dt"2026-05-07", dt"2026-04-12", 61, 8265.31, 504183.91, "Partially Delivered", "Confirmed" },
					{ "SO000130", "Q00035", "C0056", "P0003", "SG10", dt"2025-04-12", dt"2025-04-20", dt"2025-05-06", 38, 6341.55, 240978.9, "Delivered", "Confirmed" },
					{ "SO000131", "Q00033", "C0018", "P0028", "SG10", dt"2025-06-19", dt"2025-08-11", dt"2025-08-14", 80, 7686.33, 614906.4, "Partially Delivered", "Confirmed" },
					{ "SO000132", "Q00048", "C0023", "P0023", "SG10", dt"2025-04-19", dt"2025-05-23", dt"2025-06-06", 69, 2010.36, 138714.84, "Open", "Shortage" },
					{ "SO000133", "Q00074", "C0004", "P0029", "US10", dt"2026-02-15", dt"2026-03-19", dt"2026-04-23", 57, 1732.77, 98767.89, "Partially Delivered", "Confirmed" },
					{ "SO000134", "Q00096", "C0027", "P0024", "US10", dt"2025-04-25", dt"2025-06-16", dt"2025-06-24", 64, 6300.37, 403223.68, "Open", "Manual Review" },
					{ "SO000135", "Q00085", "C0053", "P0007", "DE20", dt"2026-01-27", dt"2026-03-16", dt"2026-02-27", 26, 3115.94, 81014.44, "Cancelled", "Manual Review" },
					{ "SO000136", "Q00048", "C0023", "P0008", "US10", dt"2026-02-28", dt"2026-03-26", dt"2026-04-15", 37, 1773.76, 65629.12, "Partially Delivered", "Manual Review" },
					{ "SO000137", "Q00058", "C0018", "P0032", "DE10", dt"2025-10-28", dt"2025-12-01", dt"2025-11-11", 4, 3999.15, 15996.6, "Open", "Confirmed" },
					{ "SO000138", "Q00082", "C0045", "P0013", "DE20", dt"2025-03-18", dt"2025-04-13", dt"2025-05-16", 39, 1170.4, 45645.6, "Cancelled", "Shortage" },
					{ "SO000139", "Q00069", "C0056", "P0004", "DE20", dt"2025-06-01", dt"2025-07-16", dt"2025-07-14", 51, 6539.18, 333498.18, "Cancelled", "Shortage" },
					{ "SO000140", "Q00101", "C0042", "P0020", "SG10", dt"2025-09-05", dt"2025-10-23", dt"2025-11-15", 41, 6397.03, 262278.23, "Delivered", "Manual Review" },
					{ "SO000141", "Q00048", "C0023", "P0005", "DE10", dt"2025-03-04", dt"2025-03-23", dt"2025-04-20", 38, 4961.48, 188536.24, "Partially Delivered", "Partial" },
					{ "SO000142", "Q00070", "C0025", "P0030", "SG10", dt"2025-10-20", dt"2025-11-13", dt"2025-12-07", 10, 2649.61, 26496.1, "Partially Delivered", "Manual Review" },
					{ "SO000143", "Q00086", "C0011", "P0024", "US10", dt"2025-08-04", dt"2025-09-27", dt"2025-10-10", 25, 6053.87, 151346.75, "Open", "Shortage" },
					{ "SO000144", "Q00013", "C0002", "P0034", "US10", dt"2025-05-14", dt"2025-06-28", dt"2025-06-22", 17, 3221.5, 54765.5, "Delivered", "Shortage" },
					{ "SO000145", "Q00014", "C0012", "P0031", "SG10", dt"2025-09-06", dt"2025-10-02", dt"2025-11-02", 16, 6859.87, 109757.92, "Delivered", "Confirmed" },
					{ "SO000146", "Q00055", "C0012", "P0034", "DE20", dt"2025-12-05", dt"2026-01-22", dt"2025-12-16", 65, 3976.17, 258451.05, "Delivered", "Confirmed" },
					{ "SO000147", "Q00065", "C0018", "P0023", "DE10", dt"2026-03-17", dt"2026-03-28", dt"2026-05-14", 13, 1750.99, 22762.87, "Partially Delivered", "Manual Review" },
					{ "SO000148", "Q00091", "C0046", "P0017", "DE20", dt"2026-02-03", dt"2026-03-14", dt"2026-03-19", 43, 728.8, 31338.4, "Delivered", "Manual Review" },
					{ "SO000149", "Q00017", "C0032", "P0034", "SG10", dt"2025-12-12", dt"2026-01-18", dt"2026-02-06", 52, 3140.92, 163327.84, "Partially Delivered", "Confirmed" },
					{ "SO000150", "Q00037", "C0027", "P0013", "SG10", dt"2025-06-14", dt"2025-08-13", dt"2025-06-29", 46, 1333.45, 61338.7, "Delivered", "Confirmed" },
					{ "SO000151", "Q00078", "C0010", "P0005", "SG10", dt"2025-02-25", dt"2025-04-17", dt"2025-03-23", 2, 5402.85, 10805.7, "Open", "Manual Review" },
					{ "SO000152", "Q00100", "C0005", "P0025", "US10", dt"2026-02-22", dt"2026-03-29", dt"2026-04-18", 50, 1121.87, 56093.5, "Open", "Partial" },
					{ "SO000153", "Q00042", "C0055", "P0023", "DE10", dt"2025-12-30", dt"2026-01-28", dt"2026-03-10", 28, 1820.07, 50961.96, "Partially Delivered", "Confirmed" },
					{ "SO000154", "Q00026", "C0011", "P0034", "DE20", dt"2026-01-23", dt"2026-03-12", dt"2026-02-26", 20, 3671.05, 73421.0, "Cancelled", "Manual Review" },
					{ "SO000155", "Q00048", "C0023", "P0017", "DE10", dt"2025-12-20", dt"2026-01-22", dt"2026-02-03", 32, 594.34, 19018.88, "Open", "Manual Review" },
					{ "SO000156", "Q00077", "C0019", "P0014", "SG10", dt"2025-04-18", dt"2025-05-26", dt"2025-05-30", 56, 421.06, 23579.36, "Open", "Manual Review" },
					{ "SO000157", "Q00016", "C0004", "P0005", "DE20", dt"2025-04-03", dt"2025-05-03", dt"2025-06-12", 61, 5600.27, 341616.47, "Partially Delivered", "Partial" },
					{ "SO000158", "Q00093", "C0048", "P0007", "DE20", dt"2026-03-06", dt"2026-04-23", dt"2026-05-12", 76, 3121.34, 237221.84, "Partially Delivered", "Shortage" },
					{ "SO000159", "Q00030", "C0014", "P0019", "DE10", dt"2025-10-16", dt"2025-12-07", dt"2025-11-22", 8, 1818.57, 14548.56, "Delivered", "Partial" },
					{ "SO000160", "Q00065", "C0018", "P0033", "US10", dt"2025-05-26", dt"2025-07-01", dt"2025-07-14", 51, 908.34, 46325.34, "Open", "Partial" },
					{ "SO000161", "Q00009", "C0039", "P0006", "US10", dt"2025-11-14", dt"2025-12-24", dt"2025-12-31", 26, 3192.93, 83016.18, "Open", "Confirmed" },
					{ "SO000162", "Q00039", "C0010", "P0004", "SG10", dt"2025-06-05", dt"2025-07-21", dt"2025-07-23", 10, 8056.2, 80562.0, "Partially Delivered", "Partial" },
					{ "SO000163", "Q00074", "C0004", "P0013", "SG10", dt"2025-03-18", dt"2025-05-16", dt"2025-04-22", 2, 1284.79, 2569.58, "Cancelled", "Confirmed" },
					{ "SO000164", "Q00077", "C0019", "P0016", "US10", dt"2025-02-11", dt"2025-04-06", dt"2025-03-04", 76, 5306.58, 403300.08, "Cancelled", "Partial" },
					{ "SO000165", "Q00009", "C0039", "P0036", "SG10", dt"2026-01-27", dt"2026-02-15", dt"2026-02-14", 34, 7394.52, 251413.68, "Open", "Manual Review" },
					{ "SO000166", "Q00006", "C0002", "P0009", "DE10", dt"2025-08-22", dt"2025-09-07", dt"2025-09-13", 14, 1423.92, 19934.88, "Open", "Partial" },
					{ "SO000167", "Q00071", "C0009", "P0001", "DE10", dt"2025-10-22", dt"2025-11-30", dt"2025-12-01", 73, 732.23, 53452.79, "Partially Delivered", "Confirmed" },
					{ "SO000168", "Q00090", "C0017", "P0036", "US10", dt"2025-05-16", dt"2025-06-06", dt"2025-05-30", 43, 7213.56, 310183.08, "Delivered", "Manual Review" },
					{ "SO000169", "Q00090", "C0017", "P0029", "DE20", dt"2026-01-12", dt"2026-03-05", dt"2026-02-26", 41, 2021.19, 82868.79, "Open", "Shortage" },
					{ "SO000170", "Q00014", "C0012", "P0013", "DE10", dt"2025-12-31", dt"2026-01-27", dt"2026-03-04", 45, 1393.6, 62712.0, "Delivered", "Confirmed" },
					{ "SO000171", "Q00079", "C0036", "P0032", "DE10", dt"2026-01-05", dt"2026-01-26", dt"2026-02-05", 23, 3472.23, 79861.29, "Delivered", "Confirmed" },
					{ "SO000172", "Q00079", "C0036", "P0014", "SG10", dt"2025-06-19", dt"2025-08-12", dt"2025-07-09", 60, 427.85, 25671.0, "Open", "Manual Review" },
					{ "SO000173", "Q00044", "C0054", "P0007", "SG10", dt"2026-02-03", dt"2026-03-27", dt"2026-04-10", 19, 3862.43, 73386.17, "Open", "Partial" },
					{ "SO000174", "Q00028", "C0028", "P0032", "DE10", dt"2025-05-04", dt"2025-06-23", dt"2025-06-10", 50, 3794.45, 189722.5, "Delivered", "Manual Review" },
					{ "SO000175", "Q00035", "C0056", "P0004", "DE10", dt"2025-11-06", dt"2025-12-08", dt"2025-12-01", 26, 6781.92, 176329.92, "Open", "Confirmed" },
					{ "SO000176", "Q00072", "C0045", "P0028", "DE20", dt"2025-02-07", dt"2025-03-24", dt"2025-04-17", 22, 8596.57, 189124.54, "Open", "Shortage" },
					{ "SO000177", "Q00018", "C0039", "P0011", "DE10", dt"2025-08-30", dt"2025-09-08", dt"2025-10-18", 53, 3479.05, 184389.65, "Cancelled", "Manual Review" },
					{ "SO000178", "Q00061", "C0053", "P0012", "DE20", dt"2025-10-06", dt"2025-11-05", dt"2025-10-16", 62, 6675.26, 413866.12, "Cancelled", "Manual Review" },
					{ "SO000179", "Q00040", "C0057", "P0017", "US10", dt"2025-04-21", dt"2025-06-01", dt"2025-05-31", 71, 703.61, 49956.31, "Open", "Manual Review" },
					{ "SO000180", "Q00044", "C0054", "P0010", "US10", dt"2025-05-07", dt"2025-06-13", dt"2025-07-09", 30, 7547.8, 226434.0, "Partially Delivered", "Partial" },
					{ "SO000181", "Q00009", "C0039", "P0033", "DE10", dt"2025-03-08", dt"2025-04-24", dt"2025-05-12", 43, 764.03, 32853.29, "Open", "Confirmed" },
					{ "SO000182", "Q00002", "C0036", "P0016", "DE10", dt"2025-08-15", dt"2025-08-22", dt"2025-09-04", 35, 5027.95, 175978.25, "Cancelled", "Partial" },
					{ "SO000183", "Q00031", "C0036", "P0023", "DE10", dt"2025-09-17", dt"2025-10-25", dt"2025-10-08", 46, 2134.85, 98203.1, "Partially Delivered", "Shortage" },
					{ "SO000184", "Q00038", "C0049", "P0007", "US10", dt"2026-02-19", dt"2026-04-11", dt"2026-04-16", 63, 3531.19, 222464.97, "Delivered", "Partial" },
					{ "SO000185", "Q00054", "C0024", "P0001", "DE10", dt"2025-02-17", dt"2025-03-06", dt"2025-03-17", 53, 910.52, 48257.56, "Partially Delivered", "Shortage" },
					{ "SO000186", "Q00081", "C0019", "P0001", "DE20", dt"2025-08-11", dt"2025-08-19", dt"2025-10-18", 33, 807.63, 26651.79, "Open", "Confirmed" },
					{ "SO000187", "Q00031", "C0036", "P0016", "SG10", dt"2025-11-16", dt"2025-12-05", dt"2025-11-27", 64, 5653.42, 361818.88, "Open", "Partial" },
					{ "SO000188", "Q00016", "C0004", "P0002", "DE10", dt"2026-02-25", dt"2026-03-17", dt"2026-04-15", 16, 8852.35, 141637.6, "Partially Delivered", "Partial" },
					{ "SO000189", "Q00093", "C0048", "P0029", "US10", dt"2025-10-08", dt"2025-10-17", dt"2025-10-31", 19, 1871.55, 35559.45, "Open", "Shortage" },
					{ "SO000190", "Q00062", "C0043", "P0032", "US10", dt"2025-06-25", dt"2025-07-27", dt"2025-07-11", 69, 3470.23, 239445.87, "Open", "Shortage" },
					{ "SO000191", "Q00086", "C0011", "P0032", "DE20", dt"2025-12-12", dt"2026-01-27", dt"2025-12-30", 2, 3441.53, 6883.06, "Open", "Partial" },
					{ "SO000192", "Q00048", "C0023", "P0025", "DE20", dt"2025-03-20", dt"2025-04-05", dt"2025-04-22", 20, 1019.19, 20383.8, "Open", "Shortage" },
					{ "SO000193", "Q00025", "C0046", "P0028", "DE10", dt"2025-03-01", dt"2025-04-01", dt"2025-04-11", 31, 8455.43, 262118.33, "Open", "Partial" },
					{ "SO000194", "Q00071", "C0009", "P0009", "US10", dt"2025-07-18", dt"2025-08-19", dt"2025-08-01", 69, 1283.48, 88560.12, "Delivered", "Shortage" },
					{ "SO000195", "Q00075", "C0059", "P0003", "DE20", dt"2026-02-03", dt"2026-03-28", dt"2026-04-11", 79, 6781.22, 535716.38, "Open", "Manual Review" },
					{ "SO000196", "Q00025", "C0046", "P0033", "SG10", dt"2025-07-09", dt"2025-07-20", dt"2025-08-03", 6, 921.69, 5530.14, "Cancelled", "Shortage" },
					{ "SO000197", "Q00034", "C0040", "P0009", "DE20", dt"2026-02-09", dt"2026-03-12", dt"2026-03-10", 51, 1390.89, 70935.39, "Cancelled", "Shortage" },
					{ "SO000198", "Q00046", "C0046", "P0011", "US10", dt"2025-11-20", dt"2026-01-03", dt"2025-12-30", 40, 3711.64, 148465.6, "Open", "Confirmed" },
					{ "SO000199", "Q00009", "C0039", "P0024", "US10", dt"2025-10-18", dt"2025-11-27", dt"2025-11-10", 1, 7917.9, 7917.9, "Open", "Partial" },
					{ "SO000200", "Q00005", "C0051", "P0035", "SG10", dt"2025-11-13", dt"2025-12-12", dt"2026-01-16", 38, 790.99, 30057.62, "Partially Delivered", "Manual Review" },
					{ "SO000201", "Q00099", "C0018", "P0005", "DE20", dt"2026-01-20", dt"2026-02-10", dt"2026-03-05", 42, 4821.08, 202485.36, "Cancelled", "Shortage" },
					{ "SO000202", "Q00034", "C0040", "P0009", "DE20", dt"2025-08-28", dt"2025-10-06", dt"2025-09-27", 44, 1291.79, 56838.76, "Open", "Manual Review" },
					{ "SO000203", "Q00005", "C0051", "P0024", "DE10", dt"2026-03-14", dt"2026-04-03", dt"2026-05-18", 28, 7116.1, 199250.8, "Partially Delivered", "Manual Review" },
					{ "SO000204", "Q00095", "C0057", "P0002", "SG10", dt"2025-06-01", dt"2025-07-10", dt"2025-06-12", 47, 8603.2, 404350.4, "Delivered", "Shortage" },
					{ "SO000205", "Q00085", "C0053", "P0007", "DE10", dt"2025-05-14", dt"2025-06-16", dt"2025-07-21", 19, 3372.94, 64085.86, "Delivered", "Manual Review" },
					{ "SO000206", "Q00100", "C0005", "P0017", "DE20", dt"2025-12-30", dt"2026-02-04", dt"2026-02-04", 55, 658.38, 36210.9, "Open", "Partial" },
					{ "SO000207", "Q00048", "C0023", "P0012", "US10", dt"2025-12-30", dt"2026-02-15", dt"2026-02-09", 51, 5368.23, 273779.73, "Open", "Confirmed" },
					{ "SO000208", "Q00055", "C0012", "P0014", "SG10", dt"2025-03-07", dt"2025-04-25", dt"2025-04-17", 12, 453.37, 5440.44, "Cancelled", "Shortage" },
					{ "SO000209", "Q00022", "C0049", "P0011", "US10", dt"2025-08-29", dt"2025-09-16", dt"2025-10-28", 27, 3646.77, 98462.79, "Open", "Shortage" },
					{ "SO000210", "Q00084", "C0009", "P0010", "SG10", dt"2025-11-27", dt"2026-01-01", dt"2026-01-22", 22, 6924.22, 152332.84, "Open", "Shortage" },
					{ "SO000211", "Q00021", "C0031", "P0023", "SG10", dt"2025-02-15", dt"2025-02-28", dt"2025-04-24", 33, 2008.43, 66278.19, "Delivered", "Confirmed" },
					{ "SO000212", "Q00047", "C0058", "P0007", "DE20", dt"2025-12-27", dt"2026-01-19", dt"2026-01-21", 29, 3647.81, 105786.49, "Partially Delivered", "Manual Review" },
					{ "SO000213", "Q00059", "C0047", "P0013", "SG10", dt"2025-03-16", dt"2025-04-18", dt"2025-05-19", 42, 1318.2, 55364.4, "Cancelled", "Shortage" },
					{ "SO000214", "Q00081", "C0019", "P0019", "US10", dt"2025-04-27", dt"2025-06-24", dt"2025-05-17", 59, 1664.3, 98193.7, "Open", "Confirmed" },
					{ "SO000215", "Q00039", "C0010", "P0030", "DE10", dt"2025-07-16", dt"2025-08-27", dt"2025-07-28", 49, 2602.08, 127501.92, "Cancelled", "Shortage" },
					{ "SO000216", "Q00100", "C0005", "P0022", "SG10", dt"2025-05-29", dt"2025-07-25", dt"2025-06-21", 17, 2984.2, 50731.4, "Partially Delivered", "Partial" },
					{ "SO000217", "Q00094", "C0038", "P0009", "US10", dt"2025-09-04", dt"2025-09-29", dt"2025-10-19", 40, 1448.71, 57948.4, "Open", "Confirmed" },
					{ "SO000218", "Q00051", "C0013", "P0004", "DE20", dt"2025-11-19", dt"2025-11-29", dt"2026-01-09", 39, 7596.93, 296280.27, "Open", "Manual Review" },
					{ "SO000219", "Q00040", "C0057", "P0018", "DE10", dt"2025-07-31", dt"2025-08-07", dt"2025-09-07", 18, 4642.09, 83557.62, "Open", "Manual Review" },
					{ "SO000220", "Q00013", "C0002", "P0004", "SG10", dt"2025-05-03", dt"2025-05-20", dt"2025-06-14", 37, 8392.18, 310510.66, "Delivered", "Confirmed" },
					{ "SO000221", "Q00097", "C0022", "P0009", "SG10", dt"2025-05-19", dt"2025-07-01", dt"2025-07-13", 67, 1528.67, 102420.89, "Cancelled", "Confirmed" },
					{ "SO000222", "Q00068", "C0052", "P0011", "US10", dt"2025-11-09", dt"2025-12-02", dt"2025-12-15", 27, 3548.8, 95817.6, "Open", "Confirmed" },
					{ "SO000223", "Q00072", "C0045", "P0030", "US10", dt"2025-08-19", dt"2025-10-10", dt"2025-09-23", 80, 2661.83, 212946.4, "Open", "Manual Review" },
					{ "SO000224", "Q00098", "C0045", "P0005", "SG10", dt"2025-06-24", dt"2025-07-10", dt"2025-08-20", 9, 4566.06, 41094.54, "Open", "Partial" },
					{ "SO000225", "Q00007", "C0032", "P0027", "US10", dt"2026-02-10", dt"2026-02-17", dt"2026-04-18", 75, 5708.38, 428128.5, "Cancelled", "Manual Review" },
					{ "SO000226", "Q00090", "C0017", "P0024", "DE10", dt"2025-10-13", dt"2025-11-09", dt"2025-10-27", 51, 6516.14, 332323.14, "Open", "Partial" },
					{ "SO000227", "Q00057", "C0005", "P0003", "DE20", dt"2026-03-05", dt"2026-04-13", dt"2026-05-01", 12, 7085.36, 85024.32, "Partially Delivered", "Manual Review" },
					{ "SO000228", "Q00034", "C0040", "P0007", "DE10", dt"2025-03-20", dt"2025-04-14", dt"2025-03-30", 45, 3177.87, 143004.15, "Partially Delivered", "Partial" },
					{ "SO000229", "Q00015", "C0006", "P0009", "DE10", dt"2025-05-04", dt"2025-05-17", dt"2025-06-25", 9, 1596.13, 14365.17, "Delivered", "Partial" },
					{ "SO000230", "Q00066", "C0058", "P0005", "DE10", dt"2025-12-10", dt"2025-12-23", dt"2026-02-02", 63, 4726.91, 297795.33, "Partially Delivered", "Partial" },
					{ "SO000231", "Q00038", "C0049", "P0026", "DE10", dt"2025-04-26", dt"2025-06-20", dt"2025-06-21", 11, 6156.35, 67719.85, "Delivered", "Confirmed" },
					{ "SO000232", "Q00075", "C0059", "P0034", "DE20", dt"2025-06-26", dt"2025-07-15", dt"2025-07-23", 12, 3710.55, 44526.6, "Open", "Manual Review" },
					{ "SO000233", "Q00017", "C0032", "P0020", "US10", dt"2025-08-16", dt"2025-08-30", dt"2025-09-27", 49, 6026.63, 295304.87, "Delivered", "Confirmed" },
					{ "SO000234", "Q00081", "C0019", "P0020", "DE10", dt"2026-03-11", dt"2026-04-09", dt"2026-05-05", 38, 7540.3, 286531.4, "Cancelled", "Manual Review" },
					{ "SO000235", "Q00001", "C0046", "P0014", "SG10", dt"2025-04-17", dt"2025-06-02", dt"2025-05-12", 50, 379.25, 18962.5, "Cancelled", "Confirmed" },
					{ "SO000236", "Q00070", "C0025", "P0002", "DE20", dt"2026-01-28", dt"2026-03-06", dt"2026-03-25", 32, 8049.5, 257584.0, "Partially Delivered", "Confirmed" },
					{ "SO000237", "Q00067", "C0050", "P0022", "DE10", dt"2025-09-25", dt"2025-11-24", dt"2025-11-03", 63, 2973.91, 187356.33, "Cancelled", "Manual Review" },
					{ "SO000238", "Q00013", "C0002", "P0011", "SG10", dt"2025-12-19", dt"2026-01-27", dt"2026-02-07", 29, 3365.63, 97603.27, "Delivered", "Shortage" },
					{ "SO000239", "Q00092", "C0058", "P0025", "DE10", dt"2025-05-23", dt"2025-06-28", dt"2025-07-03", 27, 1117.18, 30163.86, "Cancelled", "Shortage" },
					{ "SO000240", "Q00027", "C0017", "P0032", "DE20", dt"2025-04-18", dt"2025-06-04", dt"2025-05-19", 62, 3949.12, 244845.44, "Cancelled", "Manual Review" },
					{ "SO000241", "Q00090", "C0017", "P0010", "SG10", dt"2025-06-24", dt"2025-07-05", dt"2025-07-22", 25, 6983.33, 174583.25, "Partially Delivered", "Confirmed" },
					{ "SO000242", "Q00044", "C0054", "P0020", "US10", dt"2025-06-20", dt"2025-08-08", dt"2025-08-26", 29, 7096.75, 205805.75, "Open", "Confirmed" },
					{ "SO000243", "Q00092", "C0058", "P0030", "DE10", dt"2026-03-27", dt"2026-04-16", dt"2026-05-25", 6, 2251.67, 13510.02, "Partially Delivered", "Manual Review" },
					{ "SO000244", "Q00004", "C0029", "P0036", "US10", dt"2025-09-01", dt"2025-10-18", dt"2025-09-11", 79, 6136.87, 484812.73, "Partially Delivered", "Manual Review" },
					{ "SO000245", "Q00095", "C0057", "P0022", "DE10", dt"2025-04-08", dt"2025-05-07", dt"2025-04-21", 39, 2596.16, 101250.24, "Open", "Confirmed" },
					{ "SO000246", "Q00086", "C0011", "P0019", "DE20", dt"2025-10-11", dt"2025-10-25", dt"2025-11-05", 46, 1566.27, 72048.42, "Open", "Manual Review" },
					{ "SO000247", "Q00003", "C0051", "P0032", "DE10", dt"2025-03-28", dt"2025-05-12", dt"2025-04-15", 62, 4325.36, 268172.32, "Partially Delivered", "Confirmed" },
					{ "SO000248", "Q00029", "C0040", "P0014", "DE20", dt"2025-07-03", dt"2025-08-27", dt"2025-08-08", 73, 385.72, 28157.56, "Partially Delivered", "Manual Review" },
					{ "SO000249", "Q00057", "C0005", "P0020", "US10", dt"2025-03-02", dt"2025-04-22", dt"2025-04-06", 42, 7328.78, 307808.76, "Open", "Manual Review" },
					{ "SO000250", "Q00041", "C0050", "P0012", "DE20", dt"2025-06-23", dt"2025-08-15", dt"2025-07-20", 47, 5380.16, 252867.52, "Delivered", "Manual Review" },
					{ "SO000251", "Q00093", "C0048", "P0008", "US10", dt"2025-09-25", dt"2025-10-25", dt"2025-10-05", 50, 1368.73, 68436.5, "Delivered", "Manual Review" },
					{ "SO000252", "Q00054", "C0024", "P0025", "DE20", dt"2025-11-27", dt"2026-01-06", dt"2026-01-07", 80, 1102.34, 88187.2, "Cancelled", "Shortage" },
					{ "SO000253", "Q00089", "C0058", "P0021", "US10", dt"2025-10-13", dt"2025-11-30", dt"2025-11-22", 78, 5065.77, 395130.06, "Open", "Confirmed" },
					{ "SO000254", "Q00003", "C0051", "P0026", "SG10", dt"2025-08-20", dt"2025-10-15", dt"2025-09-09", 43, 6717.93, 288870.99, "Open", "Partial" },
					{ "SO000255", "Q00021", "C0031", "P0010", "SG10", dt"2025-07-14", dt"2025-08-23", dt"2025-08-01", 21, 7004.24, 147089.04, "Open", "Partial" },
					{ "SO000256", "Q00039", "C0010", "P0001", "DE10", dt"2026-01-14", dt"2026-03-07", dt"2026-02-03", 23, 897.75, 20648.25, "Cancelled", "Shortage" },
					{ "SO000257", "Q00082", "C0045", "P0005", "US10", dt"2025-02-16", dt"2025-02-26", dt"2025-03-03", 16, 4525.34, 72405.44, "Delivered", "Shortage" },
					{ "SO000258", "Q00078", "C0010", "P0030", "DE10", dt"2025-05-31", dt"2025-07-15", dt"2025-07-03", 51, 2259.44, 115231.44, "Open", "Shortage" },
					{ "SO000259", "Q00069", "C0056", "P0027", "DE10", dt"2026-03-02", dt"2026-04-13", dt"2026-04-17", 78, 5876.69, 458381.82, "Cancelled", "Shortage" },
					{ "SO000260", "Q00072", "C0045", "P0026", "DE20", dt"2025-07-20", dt"2025-08-10", dt"2025-09-22", 80, 5483.18, 438654.4, "Partially Delivered", "Manual Review" }
				}
			)

	measure 'Order Count' =
			COUNTROWS ( Fact_SalesOrders )
		formatString: #,0.00

	measure 'Order Value' =
			SUM ( Fact_SalesOrders[OrderValue] )
		formatString: #,0.00

	measure 'Open Backlog Value' =
			CALCULATE (
			    [Order Value],
			    Fact_SalesOrders[Status] IN { "Open", "Partially Delivered" }
			)
		formatString: #,0.00

	measure 'ATP Issue Count' =
			CALCULATE (
			    [Order Count],
			    Fact_SalesOrders[ATPStatus] <> "Confirmed"
			)
		formatString: #,0.00

	measure 'ATP Issue Rate' =
			DIVIDE ( [ATP Issue Count], [Order Count] )
		formatString: #,0.00

	measure 'Delivered Quantity' =
			SUM ( Fact_Deliveries[DeliveredQty] )
		formatString: #,0.00

	measure 'Late Or Short Deliveries' =
			CALCULATE (
			    COUNTROWS ( Fact_Deliveries ),
			    Fact_Deliveries[OTIFStatus] <> "OTIF"
			)
		formatString: #,0.00

	measure 'Late Or Short Delivery Rate' =
			DIVIDE ( [Late Or Short Deliveries], COUNTROWS ( Fact_Deliveries ) )
		formatString: #,0.00

	measure 'Invoice Amount' =
			SUM ( Fact_Billing[InvoiceAmount] )
		formatString: #,0.00

	measure 'Billing Block Count' =
			CALCULATE (
			    COUNTROWS ( Fact_Billing ),
			    Fact_Billing[BillingBlockFlag] = TRUE ()
			)
		formatString: #,0.00

	measure 'Billing Block Rate' =
			DIVIDE ( [Billing Block Count], COUNTROWS ( Fact_Billing ) )
		formatString: #,0.00

	measure 'Open AR Amount' =
			SUM ( Fact_AR[OpenAmount] )
		formatString: #,0.00

	measure 'Dispute Count' =
			CALCULATE (
			    COUNTROWS ( Fact_AR ),
			    Fact_AR[DisputeFlag] = TRUE ()
			)
		formatString: #,0.00

	measure 'O2C Exception Count' =
			COUNTROWS ( Fact_Order2CashExceptions )
		formatString: #,0.00

	measure 'O2C Exception Exposure' =
			SUM ( Fact_Order2CashExceptions[AmountExposure] )
		formatString: #,0.00

	measure 'High Severity Exceptions' =
			CALCULATE (
			    [O2C Exception Count],
			    Fact_Order2CashExceptions[Severity] = "High"
			)
		formatString: #,0.00

	measure 'Dunning Customers' =
			CALCULATE (
			    DISTINCTCOUNT ( Fact_AR[CustomerID] ),
			    Fact_AR[DunningLevel] > 0
			)
		formatString: #,0.00

	measure 'Quote Value' =
			SUM ( Fact_Quotes[QuoteValue] )
		formatString: #,0.00

	measure 'Discount Leakage' =
			SUMX ( Fact_Quotes, Fact_Quotes[QuoteValue] * Fact_Quotes[DiscountPct] / 100 )
		formatString: #,0.00

	measure 'Churn Risk Customers' =
			CALCULATE (
			    DISTINCTCOUNT ( Dim_Customer[CustomerID] ),
			    Dim_Customer[ActiveFlag] = FALSE ()
			)
		formatString: #,0.00

	measure 'Customer Churn Risk Score' =
			VAR DaysSinceLastOrder =
			    DATEDIFF (
			        CALCULATE ( MAX ( Fact_SalesOrders[OrderDate] ) ),
			        TODAY (),
			        DAY
			    )
			VAR LateEvents =
			    CALCULATE ( [ATP Issue Count] + [Late Or Short Deliveries] )
			VAR Disputes = [Dispute Count]
			RETURN
			    MIN (
			        100,
			        IF ( DaysSinceLastOrder > 180, 35, IF ( DaysSinceLastOrder > 120, 15, 0 ) )
			            + MIN ( 25, LateEvents * 5 )
			            + MIN ( 20, Disputes * 10 )
			    )
		formatString: #,0.00
