-- Plan2Produce generated DAX measure catalog
-- Demo value column: ProcessCases[ProductionValue]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total ProductionValue = SUM('ProcessCases'[ProductionValue])

Schedule Adherence = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Yield Pct = DIVIDE(CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = FALSE()), COUNTROWS('ProcessCases'))
Scrap Value = SUM('ProcessCases'[ProductionValue])
Capacity Utilization = SUM('ProcessCases'[ProductionValue])
Production Variance = SUM('ProcessCases'[ProductionValue])
