-- SupplierOnboarding2Risk generated DAX measure catalog
-- Demo value column: ProcessCases[RiskExposure]

Case Count = COUNTROWS('ProcessCases')
SLA Breach Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[SlaBreached] = TRUE())
SLA Breach Rate = DIVIDE([SLA Breach Count], [Case Count])
Action Required Count = CALCULATE(COUNTROWS('ProcessCases'), 'ProcessCases'[ActionRequired] = TRUE())
Total RiskExposure = SUM('ProcessCases'[RiskExposure])

Qualification Status = SUM('ProcessCases'[RiskExposure])
Audit Score = AVERAGE('ProcessCases'[RiskScore])
ESG Risk = AVERAGE('ProcessCases'[RiskScore])
Onboarding Aging = AVERAGE('ProcessCases'[ActualCycleDays])
Supplier Risk Exposure = AVERAGE('ProcessCases'[RiskScore])
